# Generated by Django 5.2.7 on 2026-02-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radacct',
            fields=[
                ('radacctid', models.BigAutoField(primary_key=True, serialize=False)),
                ('acctsessionid', models.CharField(max_length=64)),
                ('acctuniqueid', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('realm', models.CharField(blank=True, max_length=64, null=True)),
                ('nasipaddress', models.CharField(max_length=15)),
                ('nasportid', models.CharField(blank=True, max_length=32, null=True)),
                ('nasporttype', models.CharField(blank=True, max_length=32, null=True)),
                ('acctstarttime', models.DateTimeField(blank=True, null=True)),
                ('acctupdatetime', models.DateTimeField(blank=True, null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, null=True)),
                ('acctinterval', models.IntegerField(blank=True, null=True)),
                ('acctsessiontime', models.PositiveIntegerField(blank=True, null=True)),
                ('acctauthentic', models.CharField(blank=True, max_length=32, null=True)),
                ('connectinfo_start', models.CharField(blank=True, max_length=128, null=True)),
                ('connectinfo_stop', models.CharField(blank=True, max_length=128, null=True)),
                ('acctinputoctets', models.BigIntegerField(blank=True, null=True)),
                ('acctoutputoctets', models.BigIntegerField(blank=True, null=True)),
                ('calledstationid', models.CharField(max_length=50)),
                ('callingstationid', models.CharField(max_length=50)),
                ('acctterminatecause', models.CharField(max_length=32)),
                ('servicetype', models.CharField(blank=True, max_length=32, null=True)),
                ('framedprotocol', models.CharField(blank=True, max_length=32, null=True)),
                ('framedipaddress', models.CharField(max_length=15)),
                ('framedipv6address', models.CharField(max_length=45)),
                ('framedipv6prefix', models.CharField(max_length=45)),
                ('framedinterfaceid', models.CharField(max_length=44)),
                ('delegatedipv6prefix', models.CharField(max_length=45)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=64, null=True)),
            ],
            options={
                'db_table': 'radacct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radgroupreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radgroupreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radusergroup',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=64)),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'radusergroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pending_users',
                'managed': True,
            },
        ),
    ]
