# Generated by Django 5.2.7 on 2026-02-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'approved_users',
                'managed': True,
            },
        ),
    ]
