# Generated by Django 5.2.7 on 2026-02-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0002_approveduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_activity_logs',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
