# Generated by Django 5.2.7 on 2026-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0003_adminactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField()),
                ('source_ip', models.CharField(max_length=45)),
                ('destination_ip', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=255)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'traffic_log',
                'ordering': ['-log_time'],
                'managed': True,
            },
        ),
    ]
