# Generated by Django 5.2.7 on 2026-02-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0004_trafficlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlog',
            name='method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
