# Generated by Django 5.2.7 on 2026-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0005_alter_trafficlog_method_alter_trafficlog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='nas_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
