# Generated by Django 6.0.2 on 2026-02-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0006_trafficlog_nas_ip'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['-log_time'], name='idx_traffic_logtime'),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['nas_ip', '-log_time'], name='idx_traffic_nas_time'),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['source_ip'], name='idx_traffic_srcip'),
        ),
    ]
