# Generated by Django 6.0.2 on 2026-02-20 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0007_add_traffic_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRouterAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_ip', models.GenericIPAddressField(help_text='The NAS IP address this user is allowed to view', protocol='IPv4')),
                ('memo', models.CharField(blank=True, help_text='e.g. Branch Name', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='router_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Router Access',
                'verbose_name_plural': 'User Router Access',
                'db_table': 'user_router_access',
                'unique_together': {('user', 'router_ip')},
            },
        ),
    ]
