# Generated by Django 6.0.2 on 2026-02-20 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0008_userrouteraccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileGroup',
            fields=[
                ('groupname', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_global', models.BooleanField(default=False, help_text='If True, all branches can see/use this profile (but only Superadmin can edit)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile_group',
                'managed': True,
            },
        ),
    ]
