# Generated by Django 5.2.7 on 2026-02-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0009_userprofilegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNasAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('nasipaddress', models.GenericIPAddressField(protocol='IPv4')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_nas_assignment',
                'managed': True,
                'unique_together': {('username', 'nasipaddress')},
            },
        ),
    ]
