# Generated by Django 5.2.7 on 2026-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0010_usernasassignment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['destination_ip'], name='idx_traffic_dstip'),
        ),
    ]
