# Generated by Django 5.2.7 on 2026-03-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0011_trafficlog_idx_traffic_dstip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWebsiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nas_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('domain', models.CharField(max_length=255)),
                ('visit_count', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_website_stats',
                'managed': True,
                'indexes': [models.Index(fields=['date', 'nas_ip'], name='idx_stats_date_nas'), models.Index(fields=['domain'], name='idx_stats_domain')],
                'unique_together': {('date', 'nas_ip', 'domain')},
            },
        ),
    ]
