# Generated by Django 5.2.7 on 2026-03-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0012_dailywebsitestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywebsitestats',
            name='unique_users',
            field=models.IntegerField(default=0),
        ),
    ]
